# Generated by Django 5.0.4 on 2024-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_pending_work_sno_pending_work_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending_work',
            name='id',
        ),
        migrations.AddField(
            model_name='pending_work',
            name='sno',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
