# Generated by Django 5.0.4 on 2024-04-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_pending_work_id_pending_work_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_work',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
